name: wordgic
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flex_color_scheme: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/langbase/
    - assets/wordsets/

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/launcher.png

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#57859d"
  image: assets/launcher.png
  android: true
  ios: true
  web: true
  android12: true
